INSERT INTO tb_category (name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Food & Beverages', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Automotive', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Baby', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Beauty', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Toys and Games', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Video Games', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Mobile', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Kitchen', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Audio', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Sports and Outdoors', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Tools & Home Improvement', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Movies & Television', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Pet supplies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Women`s fashion', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Men`s fashion', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Girls` fashion', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Boys` fashion', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Health and Households', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Home and Kitchen', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Industrial and Scientific', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Luggage', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Software', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Smart Home', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Arts & Crafts', NOW());
